# Generated by Django 4.2.18 on 2025-01-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
